### PR TITLE
GitHub Add external link icon

### PR DESCRIPTION
**Pull request by maxcanna**
As requested by @demerzel3 I added an external link icon beside branch name to highlight that's a link.
Feel free to propose other icons

### CODE REVIEW

**Comment by demerzel3** [comment]
jira-icon?

**Comment by maxcanna** [comment]
That's the one I was lookin' for!

**Comment by demerzel3** [comment]
https://adespresso.hipchat.com/emoticons

**Comment by daBarbe** [comment]
With my [fixup](60e22ef) it looks good! :shipit:

**Pull request merged**
