### PR TITLE
GitHub Add JIRA issue status lozenge

### PR DESCRIPTION
**Pull request by maxcanna**
A bit WIP ATM since it interferes with GH L&F. I need your help!

### CODE REVIEW

**Comment by demerzel3** [comment]
We could move the button inside an iframe (like e.g. zendesk) thus limiting Jira's CSS scope.
I am not sure if you can inject HTML directly into an iframe or you need an URL, I will look into it.

**Comment by demerzel3** [comment]
I've pushed a fixup that uses the iframe strategy, works like a charm.
Also now the script looks for the Jira issue # in the page title as well as the branch name (to support old issues/mistakes).

The only thing I'm not sure about is whether this script should be on its own or inside `jira-issue.js`. If we interpret "jira-issue" as "jira integration for github issue page" we could put all sort of nice stuff there and reduce duplication. E.g. a linked text `AAPP-#` before the label I just added doesn't look like a bad addition.

**Comment by maxcanna** [comment]
Well done! We'll use this technique in other scripts too. 

I'm torn regarding your proposal. I thought about it and I came to the conclusion that this way it's someway modular and allows you to enable just the features that you want. Furthermore keeping small scripts is a nice to have IMHO. 

If you are worried about duplication we can put common parts (e. g. JIRA issue number detection) on a dedicated script that will expose the data via a shared variable. 

Those are just my two cents, glad to hear other thoughts.

**Comment by demerzel3** [comment]
Off-github decisions recap:
- we agree about the modularity, let's leave the choice to the users;
- the Jira status will be moved on a separate sidebar section "Jira" above "Labels", filename will be renamed in `jira-sidebar-item.js`;
- we will have a link AAPP-# before the status lozenge.

**Comment by demerzel3** [comment]
Done! Needs review :) Maybe move some of this stuff into the common script you mentioned earlier.

**Comment by demerzel3** [comment]
We could move the logic that detects the Jira issue # to a separate script added with @require.

Here's what I imagined: this common script uses waitForKeyElements to detect the Jira issue, and then fires a jquery event on `document`. This script (and `jira-issue.js`) can then listen for that event in order to manipulate the DOM.

**Comment by demerzel3** [comment]
:rotating_light: must disable scroll on the iframe:

screenshot from 2016-06-27 10-44-19

**Comment by demerzel3** [comment]
:rotating_light: when switching to "commits" or "files changed" tab:
screenshot from 2016-06-27 10-54-07

**Comment by demerzel3** [comment]
:bug: if you switch to a commit and then press the back button the Jira section becomes empty:

screenshot from 2016-06-27 11-14-44

**Comment by demerzel3** [comment]
Ok my last two commits should fix the 3 bugs above and 2 more:
- when there is no AAPP tag in the page, no error leaks to the console
- when switching to a different PR without reloading the page, the API call to Jira is correctly re-done (previously it would reuse the response from the old request instead)

Refactoring of some stuff to an external script is still to be done, but maybe we can do it in another PR.

@maxcanna needs tersting and review!

**Comment by demerzel3** [comment]
Can we merge this? I've happily used it for at least a week without problems.

**Comment by daBarbe** [comment]
I found a problem:
schermata 2016-07-06 alle 09 57 11

If there are two Jira issues we should take the last one (or both).

**Comment by demerzel3** [comment]
(mindblown)

**Comment by demerzel3** [comment]
I vote to only consider the branch name after "from", what do you think @maxcanna?

**Comment by maxcanna** [comment]
I completely agree with you. We can just replace [`.first()`](https://github.com/adespresso/monkey-tools/pull/2/files#diff-48018c57bcfd76b508765b9e545abdfeR128) with `.last()` to easily achieve that.

**Comment by daBarbe** [comment]
@demerzel3 @maxcanna I just tried with `.last()` and seems to work.

:shipit:

**Comment by maxcanna** [comment]
Squash it please

**Comment by daBarbe** [comment]
> Squash it please

Done, merge it please :trollface:

**Pull request merged**
