### PR TITLE
Add GitHub status sidebar

### PR DESCRIPTION
**Pull request by maxcanna**
#### TODO

- [x] Remove PR's branches from branches list
- [x] Map PR's statuses to lozenge classes to have the right colors
- [x] Remove existing Development pane

Ref. #3

### CODE REVIEW

**Comment by maxcanna** [comment]
Very alpha ATM.
We need to:
* Fetch GitHub CSS to have correct style (evaluate using `iframe` trick if necessary)
* Parse GitHub data
* Show it accordingly to various possible situation (branch and or PR present or not)

**Comment by demerzel3** [comment]
Very nice! Can I haz it also on the sidebar in the other views of Jira? It should be possible to match on the presence of `selectedIssue` query parameter.

**Comment by maxcanna** [comment]
@demerzel3 We've to decide if keep the original _Development_ sidebar item

**Comment by demerzel3** [comment]
IMO we should hide (or at least collapse) the original *Development* pane, sometimes I get confused and click on it and it is frustrating.

**Comment by maxcanna** [comment]
I left it to be less intrusive as possible but we can remove it if you (and the other @adespresso/developers ) like.

**Pull request merged**
