### PR TITLE
Add support for Jira BUGS project

### PR DESCRIPTION
**Pull request by daBarbe**
I want to linkify the branch name even when it is related to an issue on BUGS project

### CODE REVIEW

**Comment by demerzel3** [comment]
I don't like the idea of having to touch 3 places in the script whenever we need to support a new project.

This could be an opportunity to introduce a common configuration script, we already talked about this with @maxcanna: we could have another monkey that fires an event on `document` passing some configurations; all the real script (the ones actually doing something with the page) will react to that event and do their thing using the configuration provided.

This way  and we can make our scripts reusable to other projects/contexts/whatever. 
What do you think?

**Comment by maxcanna** [comment]
I totally agree with @demerzel3 on this!

**Comment by riquito** [comment]
@maxcanna @demerzel3 imho you're overengineering a monkey script, at least for the sake of this commit.
You could move the regular expression and the css selector ( `/^.+((AAPP|BUGS)-\d+)$/` and `.current-branch:contains('AAPP'), .current-branch:contains('BUGS')` ) to two globals or functions and minimize the future changes of this nature, without having to maintain two monkey projects. 

Since it's your project :-)  you can split it in two obviously if you like it more, but I'd open a new issue.

**Comment by maxcanna** [comment]
You'd go the _ol-dirty-way_ in this PR and defer those refactor in a future one?

**Pull request merged**
